//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaqelService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NaqelService.XMLShippingServiceSoap")]
    public interface XMLShippingServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CreateBookingAsync(NaqelService.BookingShipmentDetails _BookingShipmentDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBooking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CancelBookingAsync(NaqelService.ClientInformation ClientInfo, string RefNo, int BookingKey, string CancelReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateWaybill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CreateWaybillAsync(NaqelService.ManifestShipmentDetails _ManifestShipmentDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCommercialInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CreateCommercialInvoiceAsync(NaqelService.ClientInformation ClientInfo, NaqelService.CommercialInvoice _commercialInvoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCommercialInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.GetCommercialInvoiceResponse> GetCommercialInvoiceAsync(NaqelService.GetCommercialInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateWaybillWithPiecesBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CreateWaybillWithPiecesBarCodeAsync(NaqelService.ManifestShipmentDetails _ManifestShipmentDetails, string[] PiecesBarCodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelRTOWaybill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> CancelRTOWaybillAsync(NaqelService.ClientInformation ClientInfo, int OriginalWaybillID, int EmployID, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoadTypeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.ViwLoadTypeByClient[]> GetLoadTypeListAsync(NaqelService.ClientInformation ClientInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeClientPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> ChangeClientPasswordAsync(NaqelService.ClientInformation ClientInfo, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraceByWaybillNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Tracking[]> TraceByWaybillNoAsync(NaqelService.ClientInformation ClientInfo, int WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraceByMultiWaybillNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Tracking[]> TraceByMultiWaybillNoAsync(NaqelService.ClientInformation ClientInfo, int[] WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiWayBillTracking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.WayBillTracking[]> MultiWayBillTrackingAsync(NaqelService.ClientInformation ClientInfo, int[] WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateWaybillRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.WaybillRange> CreateWaybillRangeAsync(NaqelService.ClientInformation ClientInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWaybill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> UpdateWaybillAsync(NaqelService.ManifestShipmentDetails ManifestShipmentDetails, int WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActiveRanges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.WaybillRange[]> GetActiveRangesAsync(NaqelService.ClientInformation ClientInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRangesByClientId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.WaybillRange[]> GetRangesByClientIdAsync(int _clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsWaybillExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<bool> IsWaybillExistsAsync(NaqelService.ClientInformation ClientInfo, int WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HoldShipmentFromDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.HoldingShipmentResult> HoldShipmentFromDeliveryAsync(int WaybillNo, NaqelService.ClientInformation ClientInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWaybillNoByRefNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.Result> GetWaybillNoByRefNoAsync(string RefNo, NaqelService.ClientInformation ClientInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRTOWaybill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.RTOData> CreateRTOWaybillAsync(NaqelService.ClientInformation _ClientInfo, int WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsWaybillDelivered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<bool> IsWaybillDeliveredAsync(NaqelService.ClientInformation _ClientInfo, int WaybillNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.DefaultResult> AddNewCallAsync(NaqelService.NewCallRequest instance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWaybillSticker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.GetWaybillStickerResponse> GetWaybillStickerAsync(NaqelService.GetWaybillStickerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTrackingStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.TrackingDetails[]> SendTrackingStatusAsync(NaqelService.ClientTrackingDetails _clientTrackingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPODStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DefaultRequest))]
        System.Threading.Tasks.Task<NaqelService.PODTrackingStatus[]> GetPODStatusAsync(NaqelService.ClientInformation _clientInfo, int[] WaybillNoList);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BookingShipmentDetails
    {
        
        private ClientInformation clientInfoField;
        
        private int billingTypeField;
        
        private System.DateTime pickUpReqDateTimeField;
        
        private int picesCountField;
        
        private double weightField;
        
        private string pickUpPointField;
        
        private string specialInstructionField;
        
        private int originStationIDField;
        
        private int destinationStationIDField;
        
        private System.DateTime officeUpToField;
        
        private string contactPersonField;
        
        private string contactNumberField;
        
        private int loadTypeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientInformation ClientInfo
        {
            get
            {
                return this.clientInfoField;
            }
            set
            {
                this.clientInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BillingType
        {
            get
            {
                return this.billingTypeField;
            }
            set
            {
                this.billingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime PickUpReqDateTime
        {
            get
            {
                return this.pickUpReqDateTimeField;
            }
            set
            {
                this.pickUpReqDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PicesCount
        {
            get
            {
                return this.picesCountField;
            }
            set
            {
                this.picesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PickUpPoint
        {
            get
            {
                return this.pickUpPointField;
            }
            set
            {
                this.pickUpPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SpecialInstruction
        {
            get
            {
                return this.specialInstructionField;
            }
            set
            {
                this.specialInstructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int OriginStationID
        {
            get
            {
                return this.originStationIDField;
            }
            set
            {
                this.originStationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int DestinationStationID
        {
            get
            {
                return this.destinationStationIDField;
            }
            set
            {
                this.destinationStationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime OfficeUpTo
        {
            get
            {
                return this.officeUpToField;
            }
            set
            {
                this.officeUpToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContactNumber
        {
            get
            {
                return this.contactNumberField;
            }
            set
            {
                this.contactNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int LoadTypeID
        {
            get
            {
                return this.loadTypeIDField;
            }
            set
            {
                this.loadTypeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientInformation
    {
        
        private ClientAddress clientAddressField;
        
        private ClientContact clientContactField;
        
        private int clientIDField;
        
        private string passwordField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientAddress ClientAddress
        {
            get
            {
                return this.clientAddressField;
            }
            set
            {
                this.clientAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientContact ClientContact
        {
            get
            {
                return this.clientContactField;
            }
            set
            {
                this.clientContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientAddress
    {
        
        private string phoneNumberField;
        
        private string pOBoxField;
        
        private string zipCodeField;
        
        private string faxField;
        
        private string firstAddressField;
        
        private string locationField;
        
        private string countryCodeField;
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string POBox
        {
            get
            {
                return this.pOBoxField;
            }
            set
            {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstAddress
        {
            get
            {
                return this.firstAddressField;
            }
            set
            {
                this.firstAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CityCode
        {
            get
            {
                return this.cityCodeField;
            }
            set
            {
                this.cityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PODTrackingStatus
    {
        
        private int waybillNoField;
        
        private System.DateTime dateField;
        
        private string activityField;
        
        private bool hasErrorField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TrackingDetails
    {
        
        private int waybillNoField;
        
        private string refNoField;
        
        private System.DateTime dateField;
        
        private string activityField;
        
        private string nameField;
        
        private string firstAddressField;
        
        private string phoneNumberField;
        
        private string mobileField;
        
        private decimal numberOfPagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RefNo
        {
            get
            {
                return this.refNoField;
            }
            set
            {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstAddress
        {
            get
            {
                return this.firstAddressField;
            }
            set
            {
                this.firstAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal NumberOfPages
        {
            get
            {
                return this.numberOfPagesField;
            }
            set
            {
                this.numberOfPagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientTrackingDetails
    {
        
        private ClientInformation clientInfoField;
        
        private System.Nullable<System.DateTime> fromDateField;
        
        private System.Nullable<System.DateTime> toDateField;
        
        private int pageCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientInformation ClientInfo
        {
            get
            {
                return this.clientInfoField;
            }
            set
            {
                this.clientInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ToDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PageCount
        {
            get
            {
                return this.pageCountField;
            }
            set
            {
                this.pageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DefaultResult
    {
        
        private bool hasErrorField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewCallRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DefaultRequest
    {
        
        private int appTypeIDField;
        
        private string appVersionField;
        
        private int languageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AppTypeID
        {
            get
            {
                return this.appTypeIDField;
            }
            set
            {
                this.appTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppVersion
        {
            get
            {
                return this.appVersionField;
            }
            set
            {
                this.appVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LanguageID
        {
            get
            {
                return this.languageIDField;
            }
            set
            {
                this.languageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewCallRequest : DefaultRequest
    {
        
        private int clientIDField;
        
        private int employIDField;
        
        private string mobileNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EmployID
        {
            get
            {
                return this.employIDField;
            }
            set
            {
                this.employIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MobileNo
        {
            get
            {
                return this.mobileNoField;
            }
            set
            {
                this.mobileNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RTOData
    {
        
        private int clientIDField;
        
        private int rTOWaybillNoField;
        
        private string waybillNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RTOWaybillNo
        {
            get
            {
                return this.rTOWaybillNoField;
            }
            set
            {
                this.rTOWaybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HoldingShipmentResult
    {
        
        private bool shipmentHoldField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ShipmentHold
        {
            get
            {
                return this.shipmentHoldField;
            }
            set
            {
                this.shipmentHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WaybillRange
    {
        
        private bool hasErrorField;
        
        private int fromWaybillNoField;
        
        private int toWaybillNoField;
        
        private string messageField;
        
        public WaybillRange()
        {
            this.fromWaybillNoField = 0;
            this.toWaybillNoField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int FromWaybillNo
        {
            get
            {
                return this.fromWaybillNoField;
            }
            set
            {
                this.fromWaybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int ToWaybillNo
        {
            get
            {
                return this.toWaybillNoField;
            }
            set
            {
                this.toWaybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WayBillTracking
    {
        
        private int waybillNoField;
        
        private int clientIDField;
        
        private string orgField;
        
        private string destField;
        
        private System.DateTime pickUpDateField;
        
        private string weightField;
        
        private string consigneeNameField;
        
        private string refNoField;
        
        private System.DateTime lastEventTimeField;
        
        private string lastEventField;
        
        private string errorMessageField;
        
        private bool hasErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Org
        {
            get
            {
                return this.orgField;
            }
            set
            {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Dest
        {
            get
            {
                return this.destField;
            }
            set
            {
                this.destField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime PickUpDate
        {
            get
            {
                return this.pickUpDateField;
            }
            set
            {
                this.pickUpDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }
            set
            {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RefNo
        {
            get
            {
                return this.refNoField;
            }
            set
            {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime LastEventTime
        {
            get
            {
                return this.lastEventTimeField;
            }
            set
            {
                this.lastEventTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LastEvent
        {
            get
            {
                return this.lastEventField;
            }
            set
            {
                this.lastEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tracking
    {
        
        private string stationCodeField;
        
        private System.DateTime dateField;
        
        private int activityCodeField;
        
        private string activityField;
        
        private string arabicActivityField;
        
        private int waybillNoField;
        
        private int clientIDField;
        
        private bool hasErrorField;
        
        private string errorMessageField;
        
        private string commentsField;
        
        private string refNoField;
        
        private int deliveryStatusIDField;
        
        private string deliveryStatusMessageField;
        
        private int eventCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StationCode
        {
            get
            {
                return this.stationCodeField;
            }
            set
            {
                this.stationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ActivityCode
        {
            get
            {
                return this.activityCodeField;
            }
            set
            {
                this.activityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ArabicActivity
        {
            get
            {
                return this.arabicActivityField;
            }
            set
            {
                this.arabicActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RefNo
        {
            get
            {
                return this.refNoField;
            }
            set
            {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DeliveryStatusID
        {
            get
            {
                return this.deliveryStatusIDField;
            }
            set
            {
                this.deliveryStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DeliveryStatusMessage
        {
            get
            {
                return this.deliveryStatusMessageField;
            }
            set
            {
                this.deliveryStatusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int EventCode
        {
            get
            {
                return this.eventCodeField;
            }
            set
            {
                this.eventCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViwLoadTypeByClient
    {
        
        private int idField;
        
        private string nameField;
        
        private int serviceTypeIDField;
        
        private System.Nullable<int> clientIDField;
        
        private string serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ServiceTypeID
        {
            get
            {
                return this.serviceTypeIDField;
            }
            set
            {
                this.serviceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> ClientID
        {
            get
            {
                return this.clientIDField;
            }
            set
            {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CommercialInvoiceDetail
    {
        
        private int quantityField;
        
        private string unitTypeField;
        
        private string countryofManufactureField;
        
        private string descriptionField;
        
        private float unitCostField;
        
        private string customsCommodityCodeField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UnitType
        {
            get
            {
                return this.unitTypeField;
            }
            set
            {
                this.unitTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CountryofManufacture
        {
            get
            {
                return this.countryofManufactureField;
            }
            set
            {
                this.countryofManufactureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float UnitCost
        {
            get
            {
                return this.unitCostField;
            }
            set
            {
                this.unitCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomsCommodityCode
        {
            get
            {
                return this.customsCommodityCodeField;
            }
            set
            {
                this.customsCommodityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CommercialInvoice
    {
        
        private string refNoField;
        
        private string invoiceNoField;
        
        private System.DateTime invoiceDateField;
        
        private string consigneeField;
        
        private string consigneeAddressField;
        
        private string consigneeEmailField;
        
        private string mobileNoField;
        
        private string phoneField;
        
        private float totalCostField;
        
        private string currencyCodeField;
        
        private CommercialInvoiceDetail[] commercialInvoiceDetailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RefNo
        {
            get
            {
                return this.refNoField;
            }
            set
            {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime InvoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Consignee
        {
            get
            {
                return this.consigneeField;
            }
            set
            {
                this.consigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ConsigneeAddress
        {
            get
            {
                return this.consigneeAddressField;
            }
            set
            {
                this.consigneeAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ConsigneeEmail
        {
            get
            {
                return this.consigneeEmailField;
            }
            set
            {
                this.consigneeEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MobileNo
        {
            get
            {
                return this.mobileNoField;
            }
            set
            {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float TotalCost
        {
            get
            {
                return this.totalCostField;
            }
            set
            {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public CommercialInvoiceDetail[] CommercialInvoiceDetailList
        {
            get
            {
                return this.commercialInvoiceDetailListField;
            }
            set
            {
                this.commercialInvoiceDetailListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsigneeInformation
    {
        
        private long consigneeNationalIDField;
        
        private string consigneeNameField;
        
        private string emailField;
        
        private string mobileField;
        
        private string phoneNumberField;
        
        private string faxField;
        
        private string addressField;
        
        private string nearField;
        
        private string countryCodeField;
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ConsigneeNationalID
        {
            get
            {
                return this.consigneeNationalIDField;
            }
            set
            {
                this.consigneeNationalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }
            set
            {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Near
        {
            get
            {
                return this.nearField;
            }
            set
            {
                this.nearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CityCode
        {
            get
            {
                return this.cityCodeField;
            }
            set
            {
                this.cityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ManifestShipmentDetails
    {
        
        private ClientInformation clientInfoField;
        
        private ConsigneeInformation consigneeInfoField;
        
        private CommercialInvoice _CommercialInvoiceField;
        
        private int currenyIDField;
        
        private int billingTypeField;
        
        private int picesCountField;
        
        private double weightField;
        
        private string deliveryInstructionField;
        
        private double cODChargeField;
        
        private bool createBookingField;
        
        private bool isRTOField;
        
        private bool generatePiecesBarCodesField;
        
        private double insuredValueField;
        
        private bool isInsuranceField;
        
        private int loadTypeIDField;
        
        private double declareValueField;
        
        private string goodDescField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string refNoField;
        
        private string reference1Field;
        
        private string reference2Field;
        
        private double goodsVATAmountField;
        
        private bool isCustomDutyPayByConsigneeField;
        
        public ManifestShipmentDetails()
        {
            this.createBookingField = false;
            this.isRTOField = false;
            this.generatePiecesBarCodesField = false;
            this.insuredValueField = 0D;
            this.isInsuranceField = false;
            this.declareValueField = 0D;
            this.goodsVATAmountField = 0D;
            this.isCustomDutyPayByConsigneeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientInformation ClientInfo
        {
            get
            {
                return this.clientInfoField;
            }
            set
            {
                this.clientInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ConsigneeInformation ConsigneeInfo
        {
            get
            {
                return this.consigneeInfoField;
            }
            set
            {
                this.consigneeInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CommercialInvoice _CommercialInvoice
        {
            get
            {
                return this._CommercialInvoiceField;
            }
            set
            {
                this._CommercialInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CurrenyID
        {
            get
            {
                return this.currenyIDField;
            }
            set
            {
                this.currenyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BillingType
        {
            get
            {
                return this.billingTypeField;
            }
            set
            {
                this.billingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PicesCount
        {
            get
            {
                return this.picesCountField;
            }
            set
            {
                this.picesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DeliveryInstruction
        {
            get
            {
                return this.deliveryInstructionField;
            }
            set
            {
                this.deliveryInstructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double CODCharge
        {
            get
            {
                return this.cODChargeField;
            }
            set
            {
                this.cODChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CreateBooking
        {
            get
            {
                return this.createBookingField;
            }
            set
            {
                this.createBookingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isRTO
        {
            get
            {
                return this.isRTOField;
            }
            set
            {
                this.isRTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool GeneratePiecesBarCodes
        {
            get
            {
                return this.generatePiecesBarCodesField;
            }
            set
            {
                this.generatePiecesBarCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double InsuredValue
        {
            get
            {
                return this.insuredValueField;
            }
            set
            {
                this.insuredValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsInsurance
        {
            get
            {
                return this.isInsuranceField;
            }
            set
            {
                this.isInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int LoadTypeID
        {
            get
            {
                return this.loadTypeIDField;
            }
            set
            {
                this.loadTypeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double DeclareValue
        {
            get
            {
                return this.declareValueField;
            }
            set
            {
                this.declareValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GoodDesc
        {
            get
            {
                return this.goodDescField;
            }
            set
            {
                this.goodDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string RefNo
        {
            get
            {
                return this.refNoField;
            }
            set
            {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Reference1
        {
            get
            {
                return this.reference1Field;
            }
            set
            {
                this.reference1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Reference2
        {
            get
            {
                return this.reference2Field;
            }
            set
            {
                this.reference2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double GoodsVATAmount
        {
            get
            {
                return this.goodsVATAmountField;
            }
            set
            {
                this.goodsVATAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsCustomDutyPayByConsignee
        {
            get
            {
                return this.isCustomDutyPayByConsigneeField;
            }
            set
            {
                this.isCustomDutyPayByConsigneeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result
    {
        
        private bool hasErrorField;
        
        private int waybillNoField;
        
        private string bookingRefNoField;
        
        private int keyField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError
        {
            get
            {
                return this.hasErrorField;
            }
            set
            {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int WaybillNo
        {
            get
            {
                return this.waybillNoField;
            }
            set
            {
                this.waybillNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BookingRefNo
        {
            get
            {
                return this.bookingRefNoField;
            }
            set
            {
                this.bookingRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientContact
    {
        
        private string nameField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        private string mobileNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MobileNo
        {
            get
            {
                return this.mobileNoField;
            }
            set
            {
                this.mobileNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommercialInvoice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommercialInvoiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NaqelService.ClientInformation clientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string InvoiceNo;
        
        public GetCommercialInvoiceRequest()
        {
        }
        
        public GetCommercialInvoiceRequest(NaqelService.ClientInformation clientInfo, string InvoiceNo)
        {
            this.clientInfo = clientInfo;
            this.InvoiceNo = InvoiceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommercialInvoiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCommercialInvoiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetCommercialInvoiceResult;
        
        public GetCommercialInvoiceResponse()
        {
        }
        
        public GetCommercialInvoiceResponse(byte[] GetCommercialInvoiceResult)
        {
            this.GetCommercialInvoiceResult = GetCommercialInvoiceResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StickerSize
    {
        
        /// <remarks/>
        FourMEightInches,
        
        /// <remarks/>
        FourMSixthInches,
        
        /// <remarks/>
        A4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaybillSticker", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaybillStickerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public NaqelService.ClientInformation clientInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int WaybillNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public NaqelService.StickerSize StickerSize;
        
        public GetWaybillStickerRequest()
        {
        }
        
        public GetWaybillStickerRequest(NaqelService.ClientInformation clientInfo, int WaybillNo, NaqelService.StickerSize StickerSize)
        {
            this.clientInfo = clientInfo;
            this.WaybillNo = WaybillNo;
            this.StickerSize = StickerSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWaybillStickerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWaybillStickerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetWaybillStickerResult;
        
        public GetWaybillStickerResponse()
        {
        }
        
        public GetWaybillStickerResponse(byte[] GetWaybillStickerResult)
        {
            this.GetWaybillStickerResult = GetWaybillStickerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface XMLShippingServiceSoapChannel : NaqelService.XMLShippingServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class XMLShippingServiceSoapClient : System.ServiceModel.ClientBase<NaqelService.XMLShippingServiceSoap>, NaqelService.XMLShippingServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XMLShippingServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(XMLShippingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), XMLShippingServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLShippingServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XMLShippingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLShippingServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XMLShippingServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLShippingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CreateBookingAsync(NaqelService.BookingShipmentDetails _BookingShipmentDetail)
        {
            return base.Channel.CreateBookingAsync(_BookingShipmentDetail);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CancelBookingAsync(NaqelService.ClientInformation ClientInfo, string RefNo, int BookingKey, string CancelReason)
        {
            return base.Channel.CancelBookingAsync(ClientInfo, RefNo, BookingKey, CancelReason);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CreateWaybillAsync(NaqelService.ManifestShipmentDetails _ManifestShipmentDetails)
        {
            return base.Channel.CreateWaybillAsync(_ManifestShipmentDetails);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CreateCommercialInvoiceAsync(NaqelService.ClientInformation ClientInfo, NaqelService.CommercialInvoice _commercialInvoice)
        {
            return base.Channel.CreateCommercialInvoiceAsync(ClientInfo, _commercialInvoice);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NaqelService.GetCommercialInvoiceResponse> NaqelService.XMLShippingServiceSoap.GetCommercialInvoiceAsync(NaqelService.GetCommercialInvoiceRequest request)
        {
            return base.Channel.GetCommercialInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NaqelService.GetCommercialInvoiceResponse> GetCommercialInvoiceAsync(NaqelService.ClientInformation clientInfo, string InvoiceNo)
        {
            NaqelService.GetCommercialInvoiceRequest inValue = new NaqelService.GetCommercialInvoiceRequest();
            inValue.clientInfo = clientInfo;
            inValue.InvoiceNo = InvoiceNo;
            return ((NaqelService.XMLShippingServiceSoap)(this)).GetCommercialInvoiceAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CreateWaybillWithPiecesBarCodeAsync(NaqelService.ManifestShipmentDetails _ManifestShipmentDetails, string[] PiecesBarCodeList)
        {
            return base.Channel.CreateWaybillWithPiecesBarCodeAsync(_ManifestShipmentDetails, PiecesBarCodeList);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> CancelRTOWaybillAsync(NaqelService.ClientInformation ClientInfo, int OriginalWaybillID, int EmployID, int UserID)
        {
            return base.Channel.CancelRTOWaybillAsync(ClientInfo, OriginalWaybillID, EmployID, UserID);
        }
        
        public System.Threading.Tasks.Task<NaqelService.ViwLoadTypeByClient[]> GetLoadTypeListAsync(NaqelService.ClientInformation ClientInfo)
        {
            return base.Channel.GetLoadTypeListAsync(ClientInfo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> ChangeClientPasswordAsync(NaqelService.ClientInformation ClientInfo, string OldPassword, string NewPassword)
        {
            return base.Channel.ChangeClientPasswordAsync(ClientInfo, OldPassword, NewPassword);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Tracking[]> TraceByWaybillNoAsync(NaqelService.ClientInformation ClientInfo, int WaybillNo)
        {
            return base.Channel.TraceByWaybillNoAsync(ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Tracking[]> TraceByMultiWaybillNoAsync(NaqelService.ClientInformation ClientInfo, int[] WaybillNo)
        {
            return base.Channel.TraceByMultiWaybillNoAsync(ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.WayBillTracking[]> MultiWayBillTrackingAsync(NaqelService.ClientInformation ClientInfo, int[] WaybillNo)
        {
            return base.Channel.MultiWayBillTrackingAsync(ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.WaybillRange> CreateWaybillRangeAsync(NaqelService.ClientInformation ClientInfo)
        {
            return base.Channel.CreateWaybillRangeAsync(ClientInfo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> UpdateWaybillAsync(NaqelService.ManifestShipmentDetails ManifestShipmentDetails, int WaybillNo)
        {
            return base.Channel.UpdateWaybillAsync(ManifestShipmentDetails, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.WaybillRange[]> GetActiveRangesAsync(NaqelService.ClientInformation ClientInfo)
        {
            return base.Channel.GetActiveRangesAsync(ClientInfo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.WaybillRange[]> GetRangesByClientIdAsync(int _clientId)
        {
            return base.Channel.GetRangesByClientIdAsync(_clientId);
        }
        
        public System.Threading.Tasks.Task<bool> IsWaybillExistsAsync(NaqelService.ClientInformation ClientInfo, int WaybillNo)
        {
            return base.Channel.IsWaybillExistsAsync(ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.HoldingShipmentResult> HoldShipmentFromDeliveryAsync(int WaybillNo, NaqelService.ClientInformation ClientInfo)
        {
            return base.Channel.HoldShipmentFromDeliveryAsync(WaybillNo, ClientInfo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.Result> GetWaybillNoByRefNoAsync(string RefNo, NaqelService.ClientInformation ClientInfo)
        {
            return base.Channel.GetWaybillNoByRefNoAsync(RefNo, ClientInfo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.RTOData> CreateRTOWaybillAsync(NaqelService.ClientInformation _ClientInfo, int WaybillNo)
        {
            return base.Channel.CreateRTOWaybillAsync(_ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<bool> IsWaybillDeliveredAsync(NaqelService.ClientInformation _ClientInfo, int WaybillNo)
        {
            return base.Channel.IsWaybillDeliveredAsync(_ClientInfo, WaybillNo);
        }
        
        public System.Threading.Tasks.Task<NaqelService.DefaultResult> AddNewCallAsync(NaqelService.NewCallRequest instance)
        {
            return base.Channel.AddNewCallAsync(instance);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NaqelService.GetWaybillStickerResponse> NaqelService.XMLShippingServiceSoap.GetWaybillStickerAsync(NaqelService.GetWaybillStickerRequest request)
        {
            return base.Channel.GetWaybillStickerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NaqelService.GetWaybillStickerResponse> GetWaybillStickerAsync(NaqelService.ClientInformation clientInfo, int WaybillNo, NaqelService.StickerSize StickerSize)
        {
            NaqelService.GetWaybillStickerRequest inValue = new NaqelService.GetWaybillStickerRequest();
            inValue.clientInfo = clientInfo;
            inValue.WaybillNo = WaybillNo;
            inValue.StickerSize = StickerSize;
            return ((NaqelService.XMLShippingServiceSoap)(this)).GetWaybillStickerAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NaqelService.TrackingDetails[]> SendTrackingStatusAsync(NaqelService.ClientTrackingDetails _clientTrackingDetails)
        {
            return base.Channel.SendTrackingStatusAsync(_clientTrackingDetails);
        }
        
        public System.Threading.Tasks.Task<NaqelService.PODTrackingStatus[]> GetPODStatusAsync(NaqelService.ClientInformation _clientInfo, int[] WaybillNoList)
        {
            return base.Channel.GetPODStatusAsync(_clientInfo, WaybillNoList);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XMLShippingServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.XMLShippingServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XMLShippingServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://infotrack.naqelexpress.com/NaqelAPIServices/NaqelAPIDemo/9.0/XMLShippingS" +
                        "ervice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.XMLShippingServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://infotrack.naqelexpress.com/NaqelAPIServices/NaqelAPIDemo/9.0/XMLShippingS" +
                        "ervice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            XMLShippingServiceSoap,
            
            XMLShippingServiceSoap12,
        }
    }
}
